app/account/urls.py
from django.urls import path

from account.views import ProfileView, UserSignUpView, UserActivateView

app_name = 'account'


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
]

app/currency/api/urls.py
from rest_framework import routers

from currency.api.views import RateViewSet, SourceViewSet,  ContactUsViewSet

router = routers.SimpleRouter(trailing_slash=True)
router.register(r'rates', RateViewSet, basename='rate')
router.register(r'sources', SourceViewSet, basename='source')
router.register(r'contactus', ContactUsViewSet, basename='contactus')

app_name = 'currency_api'

urlpatterns = [
    # path('rates/', RateListAPIView.as_view(), name='rate-list'),
    # path('rates/<int:pk>/', RateDetailsAPIView.as_view(), name='rate-details'),
] + router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    RateDetailView,

    SourceListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDeleteView,
    SourceDetailView,

    ContactUsListView,
    ContactUsCreateView,
    ContactUsUpdateView,
    ContactUsDeleteView,
    ContactUsDetailView,
)

app_name = 'currency'


urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),

    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

    path('contactus/list/', ContactUsListView.as_view(), name='contactus-list'),
    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),
    path('contactus/update/<int:pk>/', ContactUsUpdateView.as_view(), name='contactus-update'),
    path('contactus/delete/<int:pk>/', ContactUsDeleteView.as_view(), name='contactus-delete'),
    path('contactus/details/<int:pk>/', ContactUsDetailView.as_view(), name='contactus-details'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from currency.views import IndexView, change_password


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('account.urls')),
    path('change-password/', change_password, name='change_password'),
    path('currency/', include('currency.urls')),

    path('api/account/', include('account.api.urls')),
    path('api/currency/', include('currency.api.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', IndexView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from currency.choices import CurrencyTypeChoices
from django.utils.translation import gettext_lazy as _


class Rate(models.Model):
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sell = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    currency_type = models.SmallIntegerField(
        choices=CurrencyTypeChoices.choices,
        default=CurrencyTypeChoices.USD
    )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')

    def __str__(self):
        return f'{self.buy} - {self.sell} - {self.source}'


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=255)
    subject = models.CharField(max_length=100)
    message = models.TextField()


class Source(models.Model):
    name = models.CharField(_('Source'), max_length=64)
    logo_source = models.FileField(_('logo'), default=None, null=True, blank=True, upload_to='logo/')
    code_name = models.CharField(_('Code name'), max_length=64, unique=True)

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    def __str__(self):
        return self.name


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=10)
    time = models.IntegerField()

app/currency/forms.py
from django import forms

from currency.models import Source, Rate, ContactUs


class SourceForm(forms.ModelForm):

    class Meta:
        model = Source
        fields = (
            'name',
            'code_name',
            'logo_source',
        )


class RateForm(forms.ModelForm):

    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'currency_type',
            'source',
        )


class ContactUsForm(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message',
        )

app/currency/api/views.py
from django.core.cache import cache
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action
from rest_framework import filters
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from currency.api.paginators import RatePagination, ContactUSPagination
from currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.api.throtling import RateThrottle
from currency.choices import CurrencyTypeChoices
from currency.constants import LATEST_RATES_CACHE_KEY
from currency.filters import RateFilter
from currency.models import Rate, Source, ContactUs


class RateViewSet(ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer  # json -> obj, obj -> json
    # renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatePagination
    filterset_class = RateFilter
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
    )
    ordering_fields = ('buy', 'sell', 'created')
    throttle_classes = (RateThrottle,)
    permission_classes = (AllowAny,)

    @action(methods=('GET',), detail=False, serializer_class=RateSerializer)
    def latest(self, request, *args, **kwargs):
        cached_data = cache.get(LATEST_RATES_CACHE_KEY)
        if cached_data is not None:
            return Response(cached_data)

        sources = Source.objects.all()

        latest_rates = []
        for source in sources:
            for currency in CurrencyTypeChoices:
                rate = Rate.objects.filter(source=source, currency_type=currency).order_by('-created').first()

                if rate is not None:
                    latest_rates.append(RateSerializer(instance=rate).data)

        cache.set(LATEST_RATES_CACHE_KEY, latest_rates, 60 * 60 * 24 * 7)  # 1 week

        return Response(latest_rates)


class SourceViewSet(ModelViewSet):
    queryset = Source.objects.all().order_by('-id')
    serializer_class = SourceSerializer


class ContactUsViewSet(ModelViewSet):
    queryset = ContactUs.objects.all().order_by('-id')
    serializer_class = ContactUsSerializer
    pagination_class = ContactUSPagination
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
        filters.SearchFilter,
    )
    search_fields = ['email_from', 'subject', 'message']

app/currency/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from currency.filters import RateFilter
from django_filters.views import FilterView
import re

from django.core.mail import send_mail
from django.views.generic import (
    ListView, CreateView, UpdateView,
    DeleteView, DetailView, TemplateView
)
from django.urls import reverse_lazy

from currency.forms import RateForm, SourceForm, ContactUsForm
from currency.models import Rate, Source, ContactUs


class RateListView(LoginRequiredMixin, FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)

        query_parameters = self.request.GET.urlencode()

        context['filter_params'] = re.sub(r'page=\d+', '', query_parameters).lstrip('&')

        return context


class RateCreateView(CreateView):
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-create')
    template_name = 'rate_create.html'


class RateUpdateView(UpdateView):
    model = Rate
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_update.html'


class RateDeleteView(DeleteView):
    model = Rate
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_delete.html'


class RateDetailView(DetailView):
    model = Rate
    template_name = 'rate_detail.html'


class SourceListView(ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class SourceCreateView(CreateView):
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-create')
    template_name = 'source_create.html'


class SourceUpdateView(UpdateView):
    model = Source
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'source_update.html'


class SourceDeleteView(DeleteView):
    model = Source
    success_url = reverse_lazy('currency:source-list')
    template_name = 'source_delete.html'


class SourceDetailView(DetailView):
    model = Source
    template_name = 'source_detail.html'


class ContactUsListView(ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus_list.html'


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = 'contactus_create.html'
    success_url = reverse_lazy('index')
    fields = (
        'email_from',
        'subject',
        'message',
    )

    def _send_email(self):
        from django.conf import settings
        recipient = settings.DEFAULT_FROM_EMAIL
        subject = 'User contact us'
        body = f'''
                Email: {self.object.email_from}
                Subject: {self.object.subject}
                Body: {self.object.message}
                '''

        send_mail(
            subject,
            body,
            recipient,
            [recipient],
            fail_silently=False,
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)

        self._send_email()

        return redirect


class ContactUsUpdateView(UpdateView):
    model = ContactUs
    form_class = ContactUsForm
    success_url = reverse_lazy('currency:contactus-list')
    template_name = 'contactus_update.html'


class ContactUsDeleteView(DeleteView):
    model = ContactUs
    success_url = reverse_lazy('currency:contactus-list')
    template_name = 'contactus_delete.html'


class ContactUsDetailView(DetailView):
    model = ContactUs
    template_name = 'contactus_detail.html'


class IndexView(TemplateView):
    template_name = 'index.html'


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'change_password.html', {'form': form})

app/currency/templates/contactus_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}ContactUs Rate{% endblock title %}

{% block content %}
    Create ContactUs Form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/contactus_delete.html
{% extends 'base.html' %}

{% block title %}ContactUs Rate{% endblock title %}

{% block content %}
    Are you sure you want to delete ContactUs with id {{ contactus.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>

{% endblock content %}

app/currency/templates/contactus_detail.html
{% extends 'base.html' %}

{%  block title %}
    ContactUs List
{% endblock title %}

{% block content %}

  Email: {{ contactus.email_from }}
  Subject:{{ contactus.subject }}
  Message:{{ contactus.message }}

{% endblock content %}

app/currency/templates/contactus_list.html
{% extends 'base.html' %}

{%  block title %}
    ContactUs List
{% endblock title %}

{% block content %}

    <a href="{% url 'currency:contactus-create' %}">Create</a><br>

{% for contactus in object_list %}
  email: {{ contactus.email_from }}
  Subject:{{ contactus.subject }}
  Message: {{ contactus.message }}

    <a href="{% url 'currency:contactus-update' contactus.id %}">Edit</a>
    <a href="{% url 'currency:contactus-delete' contactus.id %}">Delete</a>
    <a href="{% url 'currency:contactus-details' contactus.id %}">Details</a>
    <br>
{% endfor %}

{% endblock content %}

app/currency/templates/contactus_update.html
{% extends 'base.html' %}

{% block title %}ContactUs Rate{% endblock title %}

{% block content %}
    Update ContactUs Form

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}


{% block content %}

    Welcome to Currency App!

{% endblock content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create Rate{% endblock title %}

{% block content %}
    Create Rate Form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create Rate{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id {{ rate.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">Yes, delete</button>
    </form>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block title %}
    Rates List
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-12">
        <form method="get" class="form-inline mb-2">
            {{ filter.form.as_p }}
            <button type="submit" class="btn btn-primary">Применить фильтр</button>
        </form>
    </div>
</div>
    {% if user.is_authenticated %}
        <a href="{% url 'currency:rate-create' %}">Create</a><br>
    {% endif %}

    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sell</th>
                <th scope="col">Currency Type</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in page_obj %}
                <tr>
                    <th scope="row">{{ rate.id }}</th>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.sell }}</td>
                    <td>{{ rate.get_currency_type_display }}</td>
                    <td>{{ rate.source }}</td>
                    <td>
                        {% if user.is_authenticated %}
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                   data-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </a>

                                <div class="dropdown-menu">
                                    {% if user.is_superuser %}
                                        <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Edit</a>
                                        <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                    {% endif %}
                                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                </div>
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Update Rate{% endblock title %}

{% block content %}
    Update Rate Form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Source create{% endblock title %}

{% block content %}
    Create Source Form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_detail.html
{% extends 'base.html' %}

{%  block title %}
    Source List
{% endblock title %}

{% block content %}

  Name: {{ source.name }}


{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{%  block title %}
    Source List
{% endblock title %}

{% block content %}

    <a href="{% url 'currency:source-create' %}">Create</a><br>

{% for source in object_list %}
  id: {{ source.id }}
  name: {{ source.name }}
    <a href="{% url 'currency:source-update' source.id %}">Edit</a>
    <a href="{% url 'currency:source-delete' source.id %}">Delete</a>
    <a href="{% url 'currency:source-details' source.id %}">Details</a>
    <br>
{% endfor %}

{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Update Source{% endblock title %}

{% block content %}
    Update Source Form

    {% if source.logo_source %}
        <p><img style="height: 100px; width: 100px" src="{{ source.logo_source.url }}" alt="logo"></p>
    {% else %}
        <p>No logo available</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>

{% endblock content %}